-- Manifest
resource_manifest_version '77731fab-63ca-442c-a67b-abc70f28dfa5'

-- Requiring essentialmode
dependency 'essentialmode'

client_script 'carshop.lua'
client_script 'customs.lua'
server_script 'sv_carshop.lua'

ui_page 'carshop.html'

files {
	'carshop.html',
	'css/bootstrap.css',
	'css/bootstrap.min.css',
	'css/shop-homepage.css',
	'fonts/glyphicons-halflings-regular.eot',
	'fonts/glyphicons-halflings-regular.svg',
	'fonts/glyphicons-halflings-regular.ttf',
	'fonts/glyphicons-halflings-regular.woff',
	'fonts/glyphicons-halflings-regular.woff2',
	'js/bootstrap.js',
	'js/bootstrap.min.js',
	'js/jquery.js',
	'logo.jpg',
	'cursor.webp',

	-- Cars
	'cars/dominator.webp',
	'cars/mule.webp',
	'cars/benson.jpg',
	'cars/police.jpg',
	'cars/ninef.webp',
	'cars/ninef2.webp',
	'cars/prairie.webp',
	'cars/gauntlet.webp',
	'cars/voodoo.webp',
	'cars/bfinjection.webp',
	'cars/cognoscenti.webp',
	'cars/emperor.jpg',
	'cars/ingot.webp',
	'cars/alpha.webp',
	'cars/banshee.webp',
	'cars/blista2.webp',
	'cars/comet2.webp',
	'cars/elegy2.webp',
	'cars/schwarzer.webp',
	'cars/tornado2.webp',
	'cars/rancherxl.webp',
	'cars/rebel.webp',
	'cars/ztype.webp',
	'cars/adder.webp',
	'cars/fmj.webp',
	'cars/baller3.jpg',
	'cars/vacca.jpg',
	'cars/osiris.jpg',
	'cars/oracle2.jpg',
	'cars/sentinel.jpg',
	'cars/vigero.jpg',
	'cars/picador.jpg',
	'cars/buccaneer.jpg',
	'cars/sabregt.jpg',
	'cars/ruiner.jpg',
	'cars/intruder.jpg',
	'cars/premier.jpg',
	'cars/asterope.jpg',
	'cars/asea.jpg',
	'cars/washington.jpg',
	'cars/primo.jpg',
	'cars/dubsta.jpg',
	'cars/rocoto.jpg',
	'cars/patriot.jpg',
	'cars/cavalcade2.jpg',
	'cars/blazer.jpg',
	'cars/sanchez.jpg',
	'cars/scorcher.jpg',
	'cars/pounder.jpg',
	'cars/policeb.jpg',
	'cars/police3.jpg',
	'cars/sheriff2.jpg',
	'cars/casco.jpg',
	'cars/coquette2.jpg',
	'cars/feltzer3.jpg',
	'cars/towtruck.jpg',
	'cars/riot.jpg',
	'cars/baller6.jpg',
	'cars/schafter5.jpg',
	'cars/cog552.jpg',
	'cars/xls2.jpg',
	'cars/bf400.jpg',
	'cars/pcj.jpg',
	'cars/faggio.jpg',
	'cars/dominator2.jpg',
	'cars/enduro.jpg',
	'cars/shotaro.jpg',
	'cars/zombiea.jpg',
	'cars/zombieb.jpg',
	'cars/vindicator.jpg',
	'cars/jones1.jpg',
	'cars/ambulance.jpg',
	'cars/flatbed.jpg',
}
